name = "jnovel-scraper"
main = "build/index.js"
compatibility_date = "2025-11-29"

[placement]
mode = "smart"

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = true
head_sampling_rate = 1
persist = true

[dev]
ip = "0.0.0.0"
port = 8800
local_protocol = "http"

[build]
command = "cargo install -q worker-build && worker-build --release"
